import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'
import { PropsWithChildren } from "react";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'civicship',
  description: 'Generated by create next app',
};

const RootLayout: React.FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="ja">
    <body className={ `${ inter.className } min-h-screen overflow-x-hidden flex flex-col` }>
    <Header/>
    <main className="flex flex-col items-center justify-between pt-[76px] grow">
      { children }
    </main>
    <Footer/>
    </body>
    </html>
  )
};

export default RootLayout;
